### ISSUE TITLE
Plugin Config should not be written to site config

### ISSUE THREAD

**Issue by mmunz** [eRecht24/typo3-rechtstexte-plugin#3]
Currently the plugin changes site config and adds eRecht24Config parameter.

I would consider this a bad practice because:

- custom changes like @imports will most likely be lost when site config is saved
- for us site config is code which should not be changed from the backend. Also it gets deployed automatically, so every change the eRecht Plugin does there will be overwritten on the next commit.

**Comment by nmuens** [comment]
Hello Manuel,

thank you for your feedback.

You are right. We are going to check our implementation and suggest a better solution with an upcoming release.

Best wishes
Nino

**Comment by nmuens** [comment]
Hello Kay,
we are already working on a solution. I guess that we are able to release it very soon. At the moment the issue is in `development` stage. After that we are undergoing some checks and that's it.

**Comment by etlam** [comment]
Site config does not get changed any longer with v2.x of the plugin. Thanks for your contribution!
