### ISSUE TITLE
New Version for TYPO3 12.4 planned?

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [eRecht24/typo3-rechtstexte-plugin#6]
Hi all, 

do you already know when you can provide a new version for TYPO3 12.4?

thx and best regards,
Ben

**Comment by ste101** [comment]
Any news?

**Comment by etlam** [comment]
We have adopted the plugin for TYPO3 12, we are testing it this week and plan to release a new version by next week.

**Comment by etlam** [comment]
Today we were able to release a v12 compatible version:  
https://extensions.typo3.org/extension/er24_rechtstexte
