### ISSUE TITLE
E-Mail is not shown correctly in data protection

### ISSUE THREAD

**Issue by spooodesign** [eRecht24/typo3-rechtstexte-plugin#9]
There seems to be an issue with showing the emails in the data protection (TYPO3 11.5.34, er24_rechtstexte V. 2.0.2)

This is the code that is generated: 
E-mail: <a href="mailto:<a href=">privacypolicy@domain.tld</a>'&gt;<a href="mailto:privacypolicy@domain.tld">privacypolicy@domain.tld</a>

But the code should be like this: 
E-mail: <a href="mailto:privacypolicy@domain.tld">privacypolicy@domain.tld</a>

There seems to e an issue wth the viewhelper, see also screnshot. 

![Bildschirmfoto 2024-02-07 um 10 20 45](https://github.com/eRecht24/typo3-rechtstexte-plugin/assets/11443253/8ea000d3-6730-4f1d-a7e6-2d94fe9dadfb)

**Comment by LvckyAPI** [comment]
Hello @spooodesign,

thank you for your request.

I was able to reproduce the problem and have just worked out a fix.
We will run my solution through our internal quality control again and will then arrange for a new PATCH release.
